# GIT_STRATEGY: none Clone manually as a resolution of https clone is not available, and runner can't do ssh clone automatically
# Issue 3378 Uploading untracked artifacts includes ignored files, see: https://gitlab.com/gitlab-org/gitlab-runner/issues/3378
# Issue 4072 artifacts ignore paths                              , see: https://gitlab.com/gitlab-org/gitlab-ce/issues/4072

.git_refs_develop_only: &git_refs_develop_only
  only:
    - develop

.git_refs_of_snapshots: &git_refs_of_snapshots
  except:
    - master
    - /^hotfix\/.+$/
    - /^release\/.+$/
    - /^support\/.*$/
    - /^v\d+\.\d+(\.\d+)?(-\S*)?/

.git_refs_of_releases: &git_refs_of_releases
  only:
    - /^hotfix\/.+$/
    - /^release\/.+$/
    - /^support\/.*$/
    #- temp

.script_build: &script_build
  script:
    - |
      if [[ -z "${CI_OPT_MAVEN_EFFECTIVE_POM}" ]]; then export CI_OPT_MAVEN_EFFECTIVE_POM="true"; fi;
      time ./mvnw ${MAVEN_GLOBAL_SETTINGS} -e -ntp -U clean verify;
      if type -p column > /dev/null; then find .mvn/profilerReport -name "*.json" | xargs cat | jq -r '.projects[]|"module:", .project, "plugins", (.mojos[]|[.mojo,.time]|@tsv)' | column -t; fi;
      echo archive $(git ls-files -o | grep -Ev '.+-exec\.jar' | grep -v 'artifacts.tar.gz' | wc -l) files into artifacts.tar.gz;
      git ls-files -o | grep -Ev '.+-exec\.jar' | grep -v 'artifacts.tar.gz' | tar -czf artifacts.tar.gz -T -;
      #git ls-files -o | grep -Ev '.+-exec\.jar' | grep -v 'artifacts.tar.gz' | xargs rm -f;

.script_publish: &script_publish
  script:
    # force publish on temp branch push
    #- export CI_OPT_PUBLISH_TO_REPO="true";
    - |
      if [ -f artifacts.tar.gz ]; then tar -xzf artifacts.tar.gz; fi;
      export CI_OPT_MAVEN_CLEAN_SKIP="true"; export CI_OPT_SKIPITS="true"; export CI_OPT_SKIPTESTS="true";
      time ./mvnw ${MAVEN_GLOBAL_SETTINGS} -e -ntp -U -Dfast=true deploy;
      if type -p column > /dev/null; then find .mvn/profilerReport -name "*.json" | xargs cat | jq -r '.projects[]|"module:", .project, "plugins", (.mojos[]|[.mojo,.time]|@tsv)' | column -t; fi;
      echo archive $(git ls-files -o | grep -Ev '.+-exec\.jar' | grep -v 'artifacts.tar.gz' | wc -l) files into artifacts.tar.gz;
      git ls-files -o | grep -Ev '.+-exec\.jar' | grep -v 'artifacts.tar.gz' | tar -czf artifacts.tar.gz -T -;

.script_site: &script_site
  script:
    - |
      if [ -f artifacts.tar.gz ]; then tar -xzf artifacts.tar.gz; fi;
      export CI_OPT_MAVEN_CLEAN_SKIP="true"; export CI_OPT_SKIPITS="true"; export CI_OPT_SKIPTESTS="true";
      time ./mvnw ${MAVEN_GLOBAL_SETTINGS} -e -ntp site-deploy;
      if type -p column > /dev/null; then find .mvn/profilerReport -name "*.json" | xargs cat | jq -r '.projects[]|"module:", .project, "plugins", (.mojos[]|[.mojo,.time]|@tsv)' | column -t; fi;

.upload_files_for_latter_stages: &upload_files_for_latter_stages
  artifacts:
    expire_in: 1 day
    paths:
      - artifacts.tar.gz

before_script:
  - if [ -f ~/env ]; then source ~/env; fi;
  - set -ex;
  # info
  - |
    echo "HOST_HOSTNAME '${HOST_HOSTNAME}', HOST_IPADDRESS '${HOST_IPADDRESS}'";
    echo working directory `pwd`;
    echo CI_PROJECT_URL ${CI_PROJECT_URL} CI_COMMIT_REF_NAME ${CI_COMMIT_REF_NAME}, CI_COMMIT_SHA ${CI_COMMIT_SHA}, CI_PROJECT_NAME ${CI_PROJECT_NAME}, CI_PROJECT_NAMESPACE ${CI_PROJECT_NAMESPACE};
  # environment variables
  # Settings -> CI / CD -> Variables -> Expand -> Save Variables
  # CI_OPT_GPG_PASSPHRASE
  # CI_OPT_ORIGIN_REPO_SLUG
  # CI_OPT_OSSRH_DOCKER_REGISTRY_PASS
  # CI_OPT_OSSRH_DOCKER_REGISTRY_USER
  # CI_OPT_OSSRH_GIT_AUTH_TOKEN
  # CI_OPT_OSSRH_MVNSITE_PASSWORD
  # CI_OPT_OSSRH_MVNSITE_USERNAME
  # CI_OPT_OSSRH_NEXUS2_PASS
  # CI_OPT_OSSRH_NEXUS2_USER
  # CI_OPT_OSSRH_SONAR_LOGIN
  - |
    export CI_OPT_MVN_DEPLOY_PUBLISH_SEGREGATION="true";
    source circ.sh;
#  - |
#    export MAVEN_GLOBAL_SETTINGS="--global-settings ${SETTINGS_GLOBAL_XML}";
  - |
    rm -rf ~/.m2/repository/top/infra/maven/maven-build-extension;
    if [[ -z "${MAVEN_OPTS}" ]]; then export MAVEN_OPTS="-XX:+UseParallelGC -Dprofile=title -DprofileFormat=JSON,HTML"; fi;
    ls -ahl ~/.m2;
    ./mvnw ${MAVEN_GLOBAL_SETTINGS} -version;

build_snapshots:
  <<: *git_refs_of_snapshots
  <<: *script_build
  <<: *upload_files_for_latter_stages
  stage: build
  variables:
    GIT_STRATEGY: fetch

analysis:
  dependencies:
    - build_snapshots
  <<: *git_refs_develop_only
  stage: analysis
  script:
    - |
      if [ -f artifacts.tar.gz ]; then tar -xzf artifacts.tar.gz; fi;
      export CI_OPT_MAVEN_CLEAN_SKIP="true";
      time CI_OPT_SONAR="true" ./mvnw ${MAVEN_GLOBAL_SETTINGS} -e -ntp sonar:sonar;
      if type -p column > /dev/null; then find .mvn/profilerReport -name "*.json" | xargs cat | jq -r '.projects[]|"module:", .project, "plugins", (.mojos[]|[.mojo,.time]|@tsv)' | column -t; fi;
  variables:
    GIT_STRATEGY: fetch

publish_snapshots:
  dependencies:
    - build_snapshots
  <<: *git_refs_of_snapshots
  <<: *script_publish
  <<: *upload_files_for_latter_stages
  stage: publish
  variables:
    GIT_STRATEGY: fetch

site_snapshots:
  dependencies:
    - publish_snapshots
  <<: *git_refs_develop_only
  <<: *script_site
  stage: site
  variables:
    GIT_STRATEGY: fetch

build_releases:
  <<: *git_refs_of_releases
  <<: *script_build
  <<: *upload_files_for_latter_stages
  stage: build
  variables:
    GIT_STRATEGY: fetch

publish_releases:
  dependencies:
    - build_releases
  <<: *git_refs_of_releases
  <<: *script_publish
  <<: *upload_files_for_latter_stages
  stage: publish
  variables:
    GIT_STRATEGY: fetch

site_releases:
  dependencies:
    - publish_releases
  <<: *git_refs_of_releases
  <<: *script_site
  stage: site
  variables:
    GIT_STRATEGY: fetch

stages:
  - build
  - analysis
  - publish
  - site
